apiVersion: v1
kind: Service
metadata:
  name: db # referenced by the result-app internally as db
  labels:
    name: postgres-service
    app: demo-voting-app
spec:
  ports:
  - targetPort: 5432
    port: 5432
  selector:
    name: postgres-pod
    app: demo-voting-app