apiVersion: v1
kind: Service
metadata:
  name: redis # referenced by the result-app internally as redis
  labels:
    name: redis-service
    app: demo-voting-app
spec:
  ports:
  - targetPort: 6379
    port: 6379
  selector:
    name: redis-pod
    app: demo-voting-app